### ISSUE TITLE
remove cli?

### ISSUE THREAD

**Issue by tunnckoCore** [stevemao/git-raw-commits#13]
move it to `git-raw-commits-cli`?

**Comment by stevemao** [comment]
This is meant to be easier for testing... Is the package size affecting you?

**Comment by tunnckoCore** [comment]
> This is meant to be easier for testing...

Yea but not only.

> Is the package size affecting you?

Yes and no. It not make sense to install something that you dont need (meow and etc - here only meow) and counting up their "install" stats for nothing. Also one package to do one thing. CLI is totally different thing and not make sense when package is used programmatically.

**Comment by hutson** [comment]
We're closing this issue out as this repository has been merged into our [`conventional-changelog`](https://github.com/conventional-changelog/conventional-changelog) mono-repository.

If you would like to see this change incorporated into `conventional-changelog` please consider re-opening the issue against the `conventional-changelog` mono-repository.
